# Append with Column Name

In [1]:
import os
import pandas as pd


dir_root= "/home/nas/user/kbh/FaceVerification";
dir_same = "/home/nas/user/kbh/FaceVerification/same";
dir_diff = "/home/nas/user/kbh/FaceVerification/diff";

l = 0
l +=len(os.listdir(dir_root+'/same'))
l +=len(os.listdir(dir_root+'/diff'))

data =pd.DataFrame(columns={'file','label'})

data = data.append(pd.DataFrame({'file':[ dir_root+'/same/' + x for x in os.listdir(dir_same)],'label':1}),ignore_index=True)
data = data.append(pd.DataFrame({'file':[ dir_root+'/diff/' + x for x in os.listdir(dir_diff)],'label':0}),ignore_index=True)

display(data.head())
display(data.tail())

print(data.iloc[0]['file'])
print(len(data))

/home/kbh/workspace/facenet_verification/fv/lib/python3.5/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


file label
0  /home/nas/user/kbh/FaceVerification/same/kbh10...     1
1  /home/nas/user/kbh/FaceVerification/same/kbh11...     1
2  /home/nas/user/kbh/FaceVerification/same/kbh13...     1
3  /home/nas/user/kbh/FaceVerification/same/kbh14...     1
4  /home/nas/user/kbh/FaceVerification/same/kbh17...     1

file label
13675  /home/nas/user/kbh/FaceVerification/diff/kbh94...     0
13676  /home/nas/user/kbh/FaceVerification/diff/kbh9_...     0
13677  /home/nas/user/kbh/FaceVerification/diff/kbh91...     0
13678  /home/nas/user/kbh/FaceVerification/diff/kbh9_...     0
13679  /home/nas/user/kbh/FaceVerification/diff/kbh91...     0

/home/nas/user/kbh/FaceVerification/same/kbh10_kbh11.npy
13680


# Read npy data

In [3]:
import numpy as np
path = data.iloc[0]['file']
x = np.load(path)

print(x)

[ 0.00072517 -0.00631213  0.0286344   0.01322088 -0.02499864  0.02617048
  0.01385147 -0.03385998 -0.02366928  0.035698    0.01574101  0.00959557
 -0.04491548  0.03981117 -0.00753962 -0.01155773 -0.0085953  -0.00650792
 -0.00984183  0.00949219 -0.01007888 -0.02437648  0.02798963 -0.00584594
 -0.02405627 -0.00229357 -0.00630163  0.01997862 -0.02283063  0.00528472
  0.01242629  0.00795055  0.01783899  0.00572782 -0.07352088 -0.01750111
  0.0167329   0.00995452  0.02265501 -0.0221207  -0.01906023  0.01390658
  0.00554663  0.05210541  0.04557721 -0.01146079  0.02218351  0.02764705
  0.01274038 -0.00161656 -0.01057284  0.01149778  0.0188303   0.0222961
  0.02322228 -0.00389583 -0.01617895  0.03698597  0.00375309 -0.00605607
 -0.01501992 -0.01963115 -0.00267004 -0.02497401  0.03326101  0.01528397
 -0.00234157 -0.01010761 -0.00551314  0.03265359  0.00219382  0.02324248
  0.04086056  0.02377672 -0.0496764   0.0331699   0.03185865 -0.02444219
 -0.01871242  0.03380162 -0.00295171  0.01870639  0.

# Custom Dataset test

In [1]:
import FacenetGapDataset as dataset
import torch

dir_root = '/home/nas/user/kbh/FaceVerification'

data = dataset.FacenetGapDataset(dir_root)

x,y = data.__getitem__(1)
print(type(x))
print(x)


FacenetGapDataset::__init__
<class 'torch.Tensor'>
tensor([ 0.0113,  0.0087,  0.0427, -0.0171,  0.0295, -0.0189, -0.0430, -0.0154,
         0.0253,  0.0047, -0.0001, -0.0052, -0.0282,  0.0128, -0.0087, -0.0094,
        -0.0386, -0.0056,  0.0147, -0.0168,  0.0360,  0.0005,  0.0010, -0.0431,
        -0.0339,  0.0039,  0.0073, -0.0262, -0.0174, -0.0525,  0.0106, -0.0017,
         0.0312, -0.0073,  0.0194, -0.0284, -0.0107, -0.0049, -0.0297, -0.0336,
        -0.0262, -0.0221, -0.0255,  0.0254, -0.0128, -0.0144, -0.0170, -0.0050,
        -0.0264, -0.0108,  0.0028, -0.0090, -0.0123, -0.0066,  0.0269,  0.0192,
         0.0338, -0.0208, -0.0057,  0.0023, -0.0053, -0.0212,  0.0099,  0.0486,
        -0.0092, -0.0101, -0.0191, -0.0108, -0.0013, -0.0248, -0.0241, -0.0259,
         0.0389, -0.0044,  0.0079,  0.0039, -0.0097, -0.0178,  0.0315,  0.0306,
         0.0249, -0.0118, -0.0058,  0.0213, -0.0106,  0.0196, -0.0060,  0.0306,
         0.0102,  0.0245, -0.0331,  0.0192,  0.0284,  0.0247, -0.0515

# Dataloader test

In [2]:
import FacenetGapDataset as dataset
import torch
from torch.utils.data import DataLoader

dir_root = '/home/nas/user/kbh/FaceVerification'
data = dataset.FacenetGapDataset(dir_root)

dataloader = DataLoader(data, batch_size=2, shuffle=True)

FacenetGapDataset::__init__


# Predefined Dataset analysis

In [3]:
import torchvision

transform = torchvision.transforms.Compose(
    [torchvision.transforms.ToTensor(),
     torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)

x = trainset.__getitem__(1)
display(x[1])
print(type(x))
print(type(x[0]))
print(type(x[1]))

Files already downloaded and verified


9

<class 'tuple'>
<class 'torch.Tensor'>
<class 'int'>


# Test Loader

In [5]:
import FacenetGapDataset as dataset
import torch
from torch.utils.data import DataLoader

dir_root = '/home/nas/user/kbh/FaceVerification'
data = dataset.FacenetGapDataset(dir_root)
print(len(data))
dataloader = DataLoader(data, batch_size=16, shuffle=True)

dataiter = iter(dataloader)
values, label = dataiter.next()
print(values)
print(label)


FacenetGapDataset::__init__
13680
idx
11166
idx
7758
idx
12491
idx
673
idx
11658
idx
8290
idx
4337
idx
8743
idx
11757
idx
10996
idx
10457
idx
4389
idx
12187
idx
1903
idx
4205
idx
6987
tensor([[ 0.0189, -0.0314, -0.0446,  ...,  0.0517, -0.0233, -0.1034],
        [-0.0259, -0.0557,  0.0275,  ...,  0.0694, -0.0124,  0.0157],
        [-0.0048, -0.0223, -0.0152,  ...,  0.0614, -0.0151,  0.0195],
        ...,
        [-0.0303,  0.0180,  0.0108,  ..., -0.0129,  0.0139, -0.0098],
        [ 0.0103,  0.0153, -0.0118,  ..., -0.0076, -0.0227,  0.0120],
        [ 0.0028, -0.0462, -0.0174,  ...,  0.1050,  0.0094, -0.0291]])
tensor([0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0.])
